### ISSUE TITLE
Feature Request || create Ticket from Email

### ISSUE THREAD

**Issue by oneWaveAdrian** [opensupports/opensupports#64] opened 2017-09-01 08:40 UTC
It would be great if a ticket would automatically be created once a customer writes an email to our support email address.

**Comment by ivandiazwm** [comment] 2017-09-01 14:23
Yes, this feature is planned for a future release.

**Comment by oneWaveAdrian** [comment] 2017-09-04 13:59
@ivandiazwm what can I contribute to make this happen faster?

**Comment by ivandiazwm** [comment] 2017-09-04 17:43
We will probably use an IMAP library for doing this, like https://github.com/ddeboer/imap
The integration is complex, but it is our priority for v4.2 (next release).

If you need the feature as soon as possible, you can temporarily do is the following:
1. Disable the user system in your instance of OpenSupports,
2. Create an script that retrieves the inbox of your email using  IMAP/POP (you can do this using any scripting language).
3. For every new mail, take the content and make a request to `/ticket/create` (use the sender's email and the title for the email and title of the ticket respectively).
That should create a ticket every time you receive an email and the sender will be informed via email.

You can see `/ticket/create` documentation here:
https://www.opensupports.com/apidoc/#api-Ticket-Create_ticket

Hope it helps!

**Comment by EHLOVader** [comment] 2017-11-01 23:11
Would something like mailgun work well for this without requiring the imap step? 

https://www.mailgun.com/inbound-routing

**Comment by alierdogan70** [comment] 2018-08-18 20:55
I am looking forward to see this feature on this great product. In truth I am a bit surprised when I learned I does not have this feature although it has many.

**Comment by instanttim** [comment] 2018-09-24 23:27
Confusing since on opensupports.com it says you can open tickets via email. Is that aspirational?
<img width="312" alt="image" src="https://user-images.githubusercontent.com/6156678/45984597-a2ec2a80-c016-11e8-8b49-2333a75eea10.png">

**Comment by ivandiazwm** [comment] 2018-09-25 21:54
@instanttim That text was intended to describe that you can create tickets by just using your *email address* on a form. But I agree its confusing, I'll change it.

**Comment by johnshumon** [comment] 2018-10-09 17:32
Hi @ivandiazwm is this feature already part of this release opensupports_v4.3.0_update.zip or is it coming in later release?

**Comment by versavius** [comment] 2018-10-22 20:20
Just one thing to consider, you can also use pop instead of imap as that may use fewer resources but i would like one option and that would be to have the option to keep or delete emails from the mailbox.

This is for people want to keep an email trail in the mailbox or prefer the emails to be deleted once turned into a ticket.

**Comment by matthewbacon** [comment] 2018-11-28 23:46
Looking forward to this addition in v4.4 (hopefully in the next few weeks according to the Blog?)

**Comment by versavius** [comment] 2018-11-30 12:57
Interesting, I think new tickets and updates from email are key

**Comment by krisdouglas** [comment] 2018-12-20 15:21
Is there any news on the implementation of this? It's something that would really put this system up there with the rest!

**Comment by ivandiazwm** [comment] 2019-01-11 18:10
This feature is took longer than we expected and we're delayed with the release. It'll be released in a few weeks.

**Comment by ivandiazwm** [comment] 2019-03-06 17:40
This feature has been implemented, I'll add a wiki page of how to use it properly.

**Closed by ivandiazwm** 2019-03-06 17:41 UTC
Labels: enhancement, v4.4

**Comment by matthewbacon** [comment] 2019-03-06 17:53
Fantastic. Well done. Excellent timing. I look forward to exploring the new release.

**Comment by leonwlondon** [comment] 2019-08-14 18:46
Hi @ivandiazwm how can i use this feature?

**Comment by mattish91** [comment] 2020-07-12 18:27
Have this been documented in wiki yet as mentioned above? I don't seam to find it any where. Icase im just a dumb ass asking, please point me to the correct location and be nice 😂😃👍

**Comment by hoobtron** [comment] 2023-01-11 13:14
Hi @ivandiazwm any news on the documentation?
