### ISSUE TITLE
Error in step 3 of the installation of OpenSupports.

### ISSUE THREAD

**Issue by KeniaVergara** [opensupports/opensupports#711] opened 2020-01-29 15:06 UTC
An error occurred while trying to update preferences: DATABASE_CONNECTION
Please, how do I solve this error?

**Comment by ivandiazwm** [comment] 2020-02-07 01:16
It means that the provided credentials were not able to connect to the MySQL server.

Closing since duplicate of #176

**Closed by ivandiazwm** 2020-02-07 01:16 UTC
