### ISSUE TITLE
Stat table role

### ISSUE THREAD

**Issue by pfenie** [opensupports/opensupports#107] opened 2017-11-21 20:30 UTC
Hi,
I wonder what is the role of the stat table. It increments over 3000 records and blocks access to the site.
Thanks for your answer.
PF

**Comment by ivandiazwm** [comment] 2017-12-12 21:18
Stat table is used to generate statistics graphics in the default frontend client. However, this is an issue that needs to be resolver. We need to add a garbage collector of the stats (maybe we don't store more than 7 days).
This is a duplicate of #114

**Closed by ivandiazwm** 2017-12-12 21:18 UTC
