### ISSUE TITLE
Ticket not released from owner when assigning to diferent department

### ISSUE THREAD

**Issue by jcbarbosa** [opensupports/opensupports#115] opened 2017-12-14 12:50 UTC
Assigning a ticket to a different department causes ticket no to be usable.

This is because 'owner' field is not set as null on ticket table (MySQL)
Also the corresponding 'staff_ticket' record is not currently deleted

**Comment by ivandiazwm** [comment] 2017-12-15 20:05
Thanks for reporting this. I'll add it to our bug list.

**Comment by nickbe** [comment] 2018-03-28 18:13
That was a lot of moving 🤣 - so is it fixed now?

**Comment by jcbarbosa** [comment] 2018-03-28 23:33
Sorry we are not currently using this sytem anymore.
Thanks,
João

**Comment by nickbe** [comment] 2018-03-29 05:35
Well we in fact do. Therefore the question wether the bug is already fixed or not?

**Comment by ivandiazwm** [comment] 2018-03-29 15:14
The issue is fixed but it is currently on code review and need some updates

**Closed** 2018-07-03 03:34 UTC
Labels: bug
